name: JRE CI 

# This was originally the deprecated JRE release artifact workflow.
# We keep this around because it is useful for CI on the runtimer workflow.

on:
  push:
    branches:
      - '*' 
    tags:
      - 'v*'

jobs:
  build:
    # Update the SHA to test changes
    uses: yetanalytics/workflow-runtimer/.github/workflows/runtimer.yml@e0eb98e881f13d046ccaa1769be6186d1d8d5399
    with:
      java-version: '11'
      java-distribution: 'temurin'
      java-modules: 'java.base,java.logging,java.naming,java.xml,java.sql,java.transaction.xa,java.security.sasl,java.management'

  upload_artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ubuntu-latest Artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-22.04-jre

      - name: Download macOS-latest Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-14-jre

      - name: Download windows-latest Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-2022-jre
